version: '2'
services:
  web:
    build: .
    depends_on:
     - db
    ports:
     - "5000:5000"
    volumes:
     - .:/code

  db:
    image: postgres:10
    environment:
      - POSTGRES_USER=flask
      - POSTGRES_PASSWORD=flask
      - POSTGRES_DB=flask
    ports:
      - 54321:5432