"""empty message

Revision ID: 9d8e54623c74
Revises: 223301c1d9c2
Create Date: 2018-12-14 06:18:28.159235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d8e54623c74'
down_revision = '223301c1d9c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('tax_number', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=155), nullable=True),
    sa.Column('bank', sa.String(length=120), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_bank'), 'branches', ['bank'], unique=False)
    op.create_index(op.f('ix_branches_city_id'), 'branches', ['city_id'], unique=False)
    op.create_index(op.f('ix_branches_description'), 'branches', ['description'], unique=False)
    op.create_index(op.f('ix_branches_district_id'), 'branches', ['district_id'], unique=False)
    op.create_index(op.f('ix_branches_email'), 'branches', ['email'], unique=True)
    op.create_index(op.f('ix_branches_name'), 'branches', ['name'], unique=True)
    op.create_index(op.f('ix_branches_phone'), 'branches', ['phone'], unique=True)
    op.create_index(op.f('ix_branches_status'), 'branches', ['status'], unique=False)
    op.create_index(op.f('ix_branches_tax_number'), 'branches', ['tax_number'], unique=True)
    op.create_index(op.f('ix_branches_website'), 'branches', ['website'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_branches_website'), table_name='branches')
    op.drop_index(op.f('ix_branches_tax_number'), table_name='branches')
    op.drop_index(op.f('ix_branches_status'), table_name='branches')
    op.drop_index(op.f('ix_branches_phone'), table_name='branches')
    op.drop_index(op.f('ix_branches_name'), table_name='branches')
    op.drop_index(op.f('ix_branches_email'), table_name='branches')
    op.drop_index(op.f('ix_branches_district_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_description'), table_name='branches')
    op.drop_index(op.f('ix_branches_city_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_bank'), table_name='branches')
    op.drop_table('branches')
    # ### end Alembic commands ###
